#define OUT_OF_MEMORY "Out Of Memory"
#define NULLPTR "Catch Illegal Nullptr"
#define CONST_STRING "Const String Required"
#define CONST_ARRAY "Array Length Over the MAX"
#define UNKNOWN_TYPE "Unknown Type"
#define UNSUPPORT_TYPE "Unsupport Type"
#define MUST_FIND "Must find Value in Collected Got Nothing"
